on:
  push:
    branches:
      - exercise-8
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build prod
    runs-on: ubuntu-latest

  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@v2
    - run: docker build --target production --tag todo-app:production:${GITHUB_SHA::6} .
    - run: docker push benotron/todo-app:production:${GITHUB_SHA::6}
