name: Continuous Integration
on: 
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target test --tag todo-app:test .
    - run: docker run --env-file .env.test todo-app:test todo_app/tests
    - run: docker run --env-file .env todo-app:test todo_app/end_to_end_tests

